/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/


#include <cstdio>
int main()
{
    int FirstNumber = 0;
    int LastNumber =1;
    int Sum =FirstNumber+LastNumber ; 
    int FibonachiSum=0;
    int SumOfEvenNumvers =0;
     int range = 4000000;
    
    while (FibonachiSum < range)
    {
        FibonachiSum = Sum+LastNumber ;
        LastNumber = Sum;
        Sum=FibonachiSum;

      if(FibonachiSum > range)
      {
        break;
      }
      if(FibonachiSum %2 ==0)
      SumOfEvenNumvers +=FibonachiSum;
  
    }
   
    printf("Fibonacci sequence whose values do not exceed four million , the sum of the even-valued terms is : %d",SumOfEvenNumvers);
    
}